<a href="https://colab.research.google.com/github/ftomazetti/desenvolvedor-IO/blob/main/Dev_IO_Estudo1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importações de pacotes

In [18]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Numpy

In [4]:
a = np.array([1,2,3,4,5])
media = np.mean(a)
soma = np.sum(a)
contagem = np.count_nonzero(a)
print (media)
print (soma)
print (contagem)


3.0
15
5


In [5]:
semente = 42
np.random.seed(semente)

matrix = np.random.rand(3,3)
print (matrix)
print (matrix.T) ## matriz transposta


[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
[[0.37454012 0.59865848 0.05808361]
 [0.95071431 0.15601864 0.86617615]
 [0.73199394 0.15599452 0.60111501]]


# Pandas

In [8]:
data = {'Nome': ['ana', 'bruno','carla'],
        'Idade': [28,34,22],
        'salario': [5000,5100,5200]}

df = pd.DataFrame(data)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Nome     3 non-null      object
 1   Idade    3 non-null      int64 
 2   salario  3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes


In [10]:
df.describe()

,Idade,salario
count,3.0,3.0
mean,28.0,5100.0
std,6.0,100.0
min,22.0,5000.0
25%,25.0,5050.0
50%,28.0,5100.0
75%,31.0,5150.0
max,34.0,5200.0


# SciKit-Learn

In [14]:
semente = 42

x = [[1,2],[3,4],[5,6],[7,8],[9,10]]
y = [0,1,0,1,0]
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.2, random_state=semente)

In [17]:
print ("Treino: ", x_treino)
print ("Teste:", x_teste)

Treino:  [[9, 10], [5, 6], [1, 2], [7, 8]]
Teste: [[3, 4]]
